"""
Gemini service for generating AI-powered clinical summaries.

This module handles all communication with the Google Gemini API.
"""

from google import genai
import logging

from app.utils.config import GEMINI_API_KEY

# -----------------------------------------------------------------------------
# Logger
# -----------------------------------------------------------------------------

logger = logging.getLogger(__name__)

# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------

DEFAULT_MODEL = "gemini-3.1-flash-lite"

# -----------------------------------------------------------------------------
# Gemini Client
# -----------------------------------------------------------------------------

if not GEMINI_API_KEY:
    logger.error("Gemini API key is missing.")
    raise ValueError("Gemini API key is missing.")

client = genai.Client(api_key=GEMINI_API_KEY)

# -----------------------------------------------------------------------------
# Internal Helper
# -----------------------------------------------------------------------------


def _generate_response(prompt: str) -> str:
    """
    Send a prompt to Gemini and return the generated text.

    Args:
        prompt: Complete prompt sent to Gemini.

    Returns:
        Generated response text.

    Raises:
        Exception: Propagates any API or network errors.
    """

    try:
        response = client.models.generate_content(
            model=DEFAULT_MODEL,
            contents=prompt,
        )

        return response.text

    except Exception as e:
        logger.exception("Failed to generate Gemini response.")
        raise


# -----------------------------------------------------------------------------
# Public Functions
# -----------------------------------------------------------------------------


def generate_clinical_summary(transcript: str) -> str:
    """
    Generate a concise clinical summary from a consultation transcript.

    Args:
        transcript: Doctor-patient conversation transcript.

    Returns:
        Clinical summary generated by Gemini.
    """

    prompt = f"""
You are an AI clinical documentation assistant.

Your task is to generate a concise, accurate clinical summary from the consultation transcript.

Instructions:
- Use only the information present in the transcript.
- Do NOT invent symptoms, diagnoses, medications, or treatment plans.
- Do NOT make assumptions.
- Use professional clinical language.
- Keep the summary concise and well organized.

Return the output in the following format:

# Clinical Summary

## Chief Complaint
- ...

## History of Present Illness
- ...

## Pertinent Positives
- ...

## Pertinent Negatives
- ...

## Past Medical History
- ...

## Medications
- ...

## Allergies
- ...

## Social History
- ...

## Family History
- ...

## Clinical Impression
- Summarize the patient's presentation only.
- Do NOT provide a diagnosis.

## Disclaimer
This summary is AI-generated and intended for clinician review only.

Transcript:
{transcript}
"""

    return _generate_response(prompt)