"""
Gemini service for generating AI-powered clinical summaries.

This module handles all communication with the Google Gemini API.
"""

from google import genai
import logging

from app.utils.config import GEMINI_API_KEY

# -----------------------------------------------------------------------------
# Logger
# -----------------------------------------------------------------------------

logger = logging.getLogger(__name__)

# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------

DEFAULT_MODEL = "gemini-3.1-flash-lite"

# -----------------------------------------------------------------------------
# Gemini Client
# -----------------------------------------------------------------------------

if not GEMINI_API_KEY:
    logger.error("Gemini API key is missing.")
    raise ValueError("Gemini API key is missing.")

client = genai.Client(api_key=GEMINI_API_KEY)

# -----------------------------------------------------------------------------
# Internal Helper
# -----------------------------------------------------------------------------


def _generate_response(prompt: str) -> str:
    """
    Send a prompt to Gemini and return the generated text.

    Args:
        prompt: Complete prompt sent to Gemini.

    Returns:
        Generated response text.

    Raises:
        Exception: Propagates any API or network errors.
    """

    try:
        response = client.models.generate_content(
            model=DEFAULT_MODEL,
            contents=prompt,
        )

        return response.text

    except Exception as e:
        logger.exception("Failed to generate Gemini response.")
        raise


# -----------------------------------------------------------------------------
# Public Functions
# -----------------------------------------------------------------------------


def generate_clinical_summary(transcript: str) -> str:
    """
    Generate a concise clinical summary from a consultation transcript.

    Args:
        transcript: Doctor-patient conversation transcript.

    Returns:
        Clinical summary generated by Gemini.
    """

    prompt = f"""
You are an AI clinical assistant.

Generate a concise clinical summary.

Rules:
- Use professional medical language.
- Do not invent symptoms.
- Do not infer diagnoses.
- Mention only information present in the transcript.
- Keep the summary concise.
- Use bullet points where appropriate.

Transcript:
{transcript}
"""

    return _generate_response(prompt)